"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";

const steps=["Overview","Budget","Details","Confirm"];
export default function ConsultationWizard(){
  const [step,setStep]=useState(0); const [submitted,setSubmitted]=useState(false);
  if(submitted) return <div className="mx-auto max-w-3xl py-24 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[var(--accent)]"><Check/></div><h1 className="heading mt-6">Consultation request captured.</h1><p className="mt-4 text-black/60">This demo does not transmit data yet. Connect the final submit action to your CRM or API endpoint.</p></div>;
  return <div className="container-site py-16"><div className="grid gap-12 md:grid-cols-12"><aside className="md:col-span-3"><p className="eyebrow">Project intake</p><div className="mt-8 space-y-4">{steps.map((s,i)=><div key={s} className={`flex items-center gap-3 text-sm ${i===step?"font-bold":"text-black/40"}`}><span className={`grid h-7 w-7 place-items-center rounded-full border ${i<=step?"border-black bg-black text-white":"border-black/20"}`}>{i+1}</span>{s}</div>)}</div><p className="mt-8 text-sm text-black/45">Usually takes under 10 minutes.</p></aside><section className="md:col-span-9"><div className="border-t border-black/20 pt-8">{step===0&&<div><p className="eyebrow">Overview</p><h1 className="heading mt-5">Tell us about your project.</h1><p className="mt-5 max-w-xl text-black/60">A few basics help us understand scope, fit, and timing.</p><div className="mt-10 grid gap-5 md:grid-cols-2"><Field label="Project / facility type"><select className="input"><option>Commercial</option><option>Institutional</option><option>Multifamily</option><option>Industrial</option><option>Other</option></select></Field><Field label="Nature / scope of work"><input className="input" placeholder="Fit-out, retrofit, service upgrade..."/></Field><Field label="Project location"><input className="input" placeholder="City, state"/></Field><Field label="Desired start date"><input type="date" className="input"/></Field></div><Choice label="Desired completion timeline" items={["1–3 months","3–6 months","6–12 months","Flexible"]}/></div>}
{step===1&&<div><p className="eyebrow">Budget</p><h1 className="heading mt-5">Budget & expectations.</h1><Choice label="Estimated budget range" items={["Under $50K","$50K–$150K","$150K–$300K","$300K–$1M+","Not sure yet"]}/><div className="mt-8 grid gap-5 md:grid-cols-2"><Field label="What matters most?"><select className="input"><option>Schedule certainty</option><option>Budget control</option><option>Minimal disruption</option><option>Energy performance</option></select></Field><Field label="Special requirements"><input className="input" placeholder="Shutdowns, occupied site, security..."/></Field></div></div>}
{step===2&&<div><p className="eyebrow">Details</p><h1 className="heading mt-5">Project details.</h1><div className="mt-10 grid gap-5"><Field label="Project description"><textarea className="input min-h-40" placeholder="Describe the existing condition, desired outcome, constraints, and known equipment or systems."/></Field><Field label="Upload files (UI placeholder)"><input type="file" multiple className="input"/></Field></div><Choice label="Is the site currently occupied?" items={["Yes","No","Partially"]}/><Choice label="Preferred communication method" items={["Email","Phone","Text","Video call"]}/></div>}
{step===3&&<div><p className="eyebrow">Confirm</p><h1 className="heading mt-5">Contact & final confirmation.</h1><div className="mt-10 grid gap-5 md:grid-cols-2"><Field label="Full name"><input className="input" placeholder="First and last name"/></Field><Field label="Email"><input className="input" type="email" placeholder="you@example.com"/></Field><Field label="Phone"><input className="input" placeholder="Phone number"/></Field><Field label="Company"><input className="input" placeholder="Optional"/></Field><Field label="Best time to contact"><select className="input"><option>Morning</option><option>Afternoon</option><option>Evening</option></select></Field></div></div>}
<div className="mt-12 flex justify-between border-t border-black/20 pt-6"><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} className="inline-flex items-center gap-2 text-sm font-bold uppercase disabled:opacity-20"><ArrowLeft size={16}/>Back</button>{step<3?<button onClick={()=>setStep(step+1)} className="inline-flex items-center gap-2 rounded-full bg-black px-6 py-3 text-xs font-bold uppercase tracking-[.12em] text-white">Save & continue <ArrowRight size={15}/></button>:<button onClick={()=>setSubmitted(true)} className="inline-flex items-center gap-2 rounded-full bg-black px-6 py-3 text-xs font-bold uppercase tracking-[.12em] text-white">Submit consultation <ArrowRight size={15}/></button>}</div></div></section></div><style jsx global>{`.input{margin-top:.5rem;width:100%;border:1px solid rgb(0 0 0 / .22);background:transparent;padding:1rem;outline:none}.input:focus{border-color:#000}`}</style></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-medium">{label}{children}</label>}
function Choice({label,items}:{label:string;items:string[]}){return <div className="mt-9"><p className="text-sm font-medium">{label}</p><div className="mt-3 flex flex-wrap gap-2">{items.map(x=><button type="button" key={x} className="border border-black/20 px-4 py-3 text-sm hover:bg-black hover:text-white">{x}</button>)}</div></div>}
